### ISSUE TITLE
support for linux

### ISSUE THREAD

**Issue by JonnycatMeow** [VanillaEngineDevs/Vanilla-Engine#10]
will there be support for linux

**Comment by clothing-hanger** [comment]
you can run it on Linux

**Comment by JonnycatMeow** [comment]
yeah but i can't build it with the make file

**Comment by GuglioIsStupid** [comment]
you run `make lovefile` and run the love file, due to reasons there can't be an actual linux executable

**Comment by JonnycatMeow** [comment]
oh ok

**Comment by JonnycatMeow** [comment]
thank you
