### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by kiruhasas22** [VanillaEngineDevs/Vanilla-Engine#16]
Error

modules/Alphabet.lua:4: Could not open file images/png/Alphabet.png. Does not exist.

Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'newImage'
modules/Alphabet.lua:4: in main chunk
[C]: in function 'require'
main.lua:224: in function 'load'
[love "callbacks.lua"]:136: in function <[love "callbacks.lua"]:135>
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by GuglioIsStupid** [comment]
Im not home currently, but i know the issue!

Simply go to modules/Alphabet.lua and for the loading change "Alphabet" to "alphabet" (make it all lowercase)

**Comment by GuglioIsStupid** [comment]
It slipped pass me because i wasn't able to test a compiled build yet, when I'm home, ill make sure to fix it!

**Comment by GuglioIsStupid** [comment]
Fixed in e3112ee8b0e3cd98a3d81af66781359941a46972
