### ISSUE TITLE
.ogg files not found?

### ISSUE THREAD

**Issue by TheRealPepsi** [VanillaEngineDevs/Vanilla-Engine#17]
Hey all, having this issue where every song I load, can't load due to it not finding the .ogg. What do I do? 
![Here's a screenshot of the error](https://github.com/VanillaEngineDevs/Vanilla-Engine/assets/134110892/09a3e296-09fd-4874-a573-25783f554da2)

**Comment by GuglioIsStupid** [comment]
Fixed in 0c50acfaef860a7f7af03c79f9a7fac79c6d1710
