### ISSUE TITLE
[Switch] Multiple Glitches

### ISSUE THREAD

**Issue by Matthew-MBG** [VanillaEngineDevs/Vanilla-Engine#20]
[Week 2] Monster causes a crash (FP + Story)
[Week 5] Simply  crashes due to missing file sounds/lights-off.ogg
[Week 7] Cutscenes are ultra laggy

**Comment by GuglioIsStupid** [comment]
Wuestion- what do you mean by messed up inputs?

**Comment by GuglioIsStupid** [comment]
Nothing I can do about the cutscenes, videos just suck lol
