### ISSUE TITLE
game  crash as i open it

### ISSUE THREAD

**Issue by pixelverseyeah** [VanillaEngineDevs/Vanilla-Engine#21]
ve just crashes anytime when I open

error code 
Error: lib/ini.lua:56: attempt to index a nil value
stack traceback:
        [love "boot.lua"]:352: in function '__index'
        lib/ini.lua:56: in function 'readKey'
        settings.lua:204: in main chunk
        [C]: in function 'require'
        main.lua:232: in function 'load'
        modules/overrides.lua:12: in function <modules/overrides.lua:3>
        [C]: in function 'xpcall'
        [love "boot.lua"]:368: in function <[love "boot.lua"]:355>
        [C]: in function 'xpcall'

**Comment by GuglioIsStupid** [comment]
idk why it does that when i mention the issue, but try the latest commit/nightly (no switch build for it)

**Comment by pixelverseyeah** [comment]
that coming form the nightly build

**Comment by GuglioIsStupid** [comment]
I am saying to test the newest one

**Comment by pixelverseyeah** [comment]
plus it does the same stuff in the source code

**Comment by pixelverseyeah** [comment]
> I am saying to test the newest one

the new ones fine it just dev/nightly builds

**Comment by GuglioIsStupid** [comment]
Fixed in a116d98
