### ISSUE TITLE
[Switch] Options menu (Versión 1.1.2h)

### ISSUE THREAD

**Issue by RetroMarioBros** [VanillaEngineDevs/Vanilla-Engine#23]
First of all, thank you for this work.
The options menu appears cut off, and not all the letters can be read.
This may be due to the size of the pink background, which appears smaller than the menu.

![IMG_20240828_082109](https://github.com/user-attachments/assets/d7a08e86-b9e2-4146-9bb3-15268fa16aaf)
![IMG_20240828_082046](https://github.com/user-attachments/assets/1545edcf-1232-4ba0-95a7-1ebf9fd0fe10)
![IMG_20240828_082057](https://github.com/user-attachments/assets/86309561-2e09-40aa-85cb-ac9ebebe9f10)
![IMG_20240828_082034](https://github.com/user-attachments/assets/debbc7a8-9493-45c5-97f9-d43eb50d5f7b)

**Comment by GuglioIsStupid** [comment]
I unfortunately cannot recreate this issue, can you give the steps required to recreate the issue?

**Comment by GuglioIsStupid** [comment]
nvm found the issue

**Comment by RetroMarioBros** [comment]
Oh great! Thanks a lot
I'm looking forward to trying the new version with these bugs fixed, when you release the next version

**Comment by GuglioIsStupid** [comment]
Next release will be sometime after Sept 12 (Pico remixes update)

**Comment by RetroMarioBros** [comment]
Thanks you!!!! 🎉🎉
