### ISSUE TITLE
gamejolt not working on macos 

### ISSUE THREAD

**Issue by JonnycatMeow** [VanillaEngineDevs/Vanilla-Engine#4]
Error

lib/gamejolt/init.lua:58: attempt to index upvalue 'f' (a nil value)

Traceback

[love "callbacks.lua"]:228: in function 'handler'
lib/gamejolt/init.lua:58: in function 'on'
lib/gamejolt/init.lua:44: in function 'parseKeypair'
lib/gamejolt/init.lua:52: in function 'handleTrophies'
lib/gamejolt/init.lua:224: in function 'fetchAllTrophies'
lib/gamejolt/init.lua:204: in function 'giveTrophy'
states/menu/menu.lua:47: in function 'switch'
states/gjlogin.lua:42: in function 'func'
modules/graphics.lua:580: in function 'after'
lib/timer.lua:45: in function 'updateTimerHandle'
lib/timer.lua:64: in function 'update'
main.lua:812: in function 'update'
[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'

**Comment by JonnycatMeow** [comment]
![Screen Shot 2022-11-01 at 6 39 27 PM](https://user-images.githubusercontent.com/107599365/199374509-4ffb18d7-0f99-4de0-9931-ceee099bb746.png)
wow

**Comment by GuglioIsStupid** [comment]
thats weird cuz it seemed to work but you cant play

**Comment by JonnycatMeow** [comment]
oh wait

**Comment by GuglioIsStupid** [comment]
oh alr

**Comment by JonnycatMeow** [comment]
love it
