### ISSUE TITLE
i tried to save my keybinds and it crash

### ISSUE THREAD

**Issue by JonnycatMeow** [VanillaEngineDevs/Vanilla-Engine#6]
![Screen Shot 2022-11-01 at 6 45 36 PM](https://user-images.githubusercontent.com/107599365/199375276-6e61219b-1402-4ce1-b63f-441dd7ff2916.png)

**Comment by GuglioIsStupid** [comment]
line 635 is settings.window.windowWidth

seems to be an issue of settings.window not saving properly
![image](https://user-images.githubusercontent.com/96344386/199375533-d37ca728-c35e-4a62-a10a-ccb1fecfb59c.png)

**Comment by GuglioIsStupid** [comment]
I just tested with a wiped settings file
window stuff seems to not save when doing keybinds, will be fixed very soon

**Comment by JonnycatMeow** [comment]
thx

**Comment by GuglioIsStupid** [comment]
Fixed (see [3b193c274994046d767502b78548669ef239263b](https://github.com/VanillaEngineDevs/Vanilla-Engine/commit/3b193c274994046d767502b78548669ef239263b) )

**Comment by GuglioIsStupid** [comment]
Please delete the settings file in your save folder

**Comment by JonnycatMeow** [comment]
oh ok

**Comment by GuglioIsStupid** [comment]
Any update on this?

**Comment by JonnycatMeow** [comment]
yeah its fixed

**Comment by JonnycatMeow** [comment]
also are you gonna add hxcodec to your engine? its a video player

**Comment by JonnycatMeow** [comment]
https://github.com/polybiusproxy/hxCodec

**Comment by GuglioIsStupid** [comment]
Vanilla Engine does not use haxeflixel code whatsoever, besides videos are supported via [love.video](https://love2d.org/wiki/love.video)
VE is purely Lua + LOVE
