### ISSUE TITLE
Crash in Vanilla Engine v1.0.0

### ISSUE THREAD

**Issue by Getsaa** [VanillaEngineDevs/Vanilla-Engine#7]
Vanilla Engine has crashed with the following error:

```
weeks/week7.lua:343: attempt to compare nil with number
stack traceback:
main.lua:30: in function 'handler'
[love boot.lua]:345: in function '__lt'
weeks/week7.lua:343: in function 'update'
main.lua:855: in function 'update'
[love callbacks.lua]:162: in function <[love callbacks.lua]:144>
[C]: in function 'xpcall'
[love boot.lua]:370: in function <[love boot.lua]:337>
```

[If you can, describe what you've been doing when the error occurred]
HII IDK WH AT THE FUCKJ JJUST HAPPPENDE I I JUST LIKE IT UHH IT FUCKING CRASHED WHEN I TRIED TO PAUSE THE GAME AND UHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH hi
---
Affects: v1.0.0
Edition: Windows

**Comment by GuglioIsStupid** [comment]
oh this is a known error, i still have to fix this

**Comment by Getsaa** [comment]
> oh this is a known error, i still have to fix this it specifically happens on freeplay for sum reason

ohok

**Comment by Getsaa** [comment]
> oh this is a known error, i still have to fix this it specifically happens on freeplay for sum reason

ohok
